// AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

import { config } from 'dotenv';
import { AnthropicVertex, MessageParam, Message } from 'anthropic';
import { dataclass, field } from 'dataclass-decorator';
import { swagger } from 'swagger-express-ts';

// Importing fastcore, nbdev equivalents or alternatives
// Note: These libraries might not have direct TypeScript equivalents
// You may need to implement or find alternatives for these functionalities
// import { basics, test, foundation } from 'fastcore-ts';
// import { showDoc } from 'nbdev-ts';

@dataclass
class LazyState {
    problem: string;
    steps: string[] = field(() => []);
    currentStep: number = 0;

    constructor(problem: string) {
        this.problem = problem;
        this.steps.push(problem);
    }

    addStep(step: string): void {
        this.steps.push(step);
        this.currentStep++;
    }

    getContext(): string {
        return `Problem: ${this.problem} \n Steps so far: ${this.steps}`;
    }

    refresh(): void {
        this.currentStep = 0;
        this.steps = [this.problem];
    }
}

@dataclass
class LLM {
    client: AnthropicVertex;
    model: string;
}

const lazySystemP = `
You are a helpful assistant that can help with math problems.
You will be given a problem and a list of steps as context, the format will be:
        
PROBLEM: <problem>
STEPS: <steps>

Your job is to complete the next step and only the next step in the problem-solving process. You should never give more than one step.
If you evaluate that the problem is done, respond with "PROBLEM DONE"
`;

@swagger.tags('LazyEvaluationClient')
class LazyEvaluationClient {
    private model: string;
    private client: AnthropicVertex;
    private maxTokens: number;
    private state: LazyState | null;
    private lazySystemP: string;
    private questionHistory: string[];

    constructor(
        llm: LLM,
        maxTokens: number = 100,
        state: LazyState | null = null,
        lazySystemP: string = lazySystemP
    ) {
        this.model = llm.model;
        this.client = llm.client;
        this.maxTokens = maxTokens;
        this.state = state;
        this.lazySystemP = lazySystemP;
        this.questionHistory = [];
    }

    @swagger.apiOperation({ summary: 'Initialize a new problem' })
    @swagger.apiParam({ name: 'problem', description: 'The problem to initialize', required: true, type: 'string' })
    initalizeProblem(problem: string): void {
        this.state = new LazyState(problem);
    }

    @swagger.apiOperation({ summary: 'Get the current step' })
    @swagger.apiResponse({ status: 200, description: 'The current step', type: 'string' })
    getCurrentStep(): string {
        if (!this.state) {
            throw new Error("Problem is not initialized, call initalizeProblem first");
        }
        return this.state.steps[this.state.currentStep];
    }

    @swagger.apiOperation({ summary: 'Get the next step' })
    @swagger.apiResponse({ status: 200, description: 'The next step', type: 'string' })
    async getNextStep(): Promise<string> {
        if (!this.state) {
            throw new Error("Problem is not initialized, call initalizeProblem first");
        }

        const messages: MessageParam[] = [
            {
                role: "user",
                content: this.state.getContext()
            }
        ];

        const response: Message = await this.client.messages.create({
            system: this.lazySystemP,
            model: this.model,
            messages: messages,
            max_tokens: this.maxTokens
        });

        const nextStep = response.content[0].text;
        if (nextStep) {
            this.state.addStep(nextStep.trim());
            return nextStep.trim();
        } else {
            throw new Error("No next step found");
        }
    }

    @swagger.apiOperation({ summary: 'Ask a question about the current step' })
    @swagger.apiParam({ name: 'question', description: 'The question to ask', required: true, type: 'string' })
    @swagger.apiResponse({ status: 200, description: 'The answer to the question', type: 'string' })
    async askQuestion(question: string): Promise<string> {
        if (!this.state) {
            throw new Error("Problem is not initialized, call initalizeProblem first");
        }

        const currentState = `
            System: ${this.lazySystemP}
            Problem: ${this.state.problem}
            Context: ${this.state.getContext()}
            Current step: ${this.state.steps[this.state.currentStep]}
        `;

        const prompt = `
            Question History: ${this.questionHistory}
            Question: ${question}
            Please answer the question without advancing to the next step.
            If you are asked to provide an example for a specific step, please provide an example that is not in the current context.
        `;

        const messages: MessageParam[] = [
            {
                role: "user",
                content: prompt
            }
        ];

        const response: Message = await this.client.messages.create({
            system: currentState,
            model: this.model,
            messages: messages,
            max_tokens: this.maxTokens
        });

        const answer = response.content[0].text.trim();
        this.questionHistory.push(question);
        this.questionHistory.push(answer);

        return answer;
    }
}

// Extending AnthropicVertex prototype
declare module 'anthropic' {
    interface AnthropicVertex {
        lazy(problem: string): LazyEvaluationClient;
    }
}

AnthropicVertex.prototype.lazy = function(problem: string): LazyEvaluationClient {
    const state = new LazyState(problem);
    const llm = new LLM(this, "claude-3-5-sonnet@20240620");
    return new LazyEvaluationClient(llm, 100, state);
};

export { LazyState, LLM, LazyEvaluationClient, lazySystemP };